export const PUNISHMENT_TYPE = {
  WARNING: 1,
  MUTE_1D: 2,
  MUTE_3D: 3,
  MUTE_7D: 4,
  PERMANENT_MUTE: 5,
  BAN: 6
}

export const PUNISHMENT_LABEL = {
  [PUNISHMENT_TYPE.WARNING]: '警告',
  [PUNISHMENT_TYPE.MUTE_1D]: '禁言1天',
  [PUNISHMENT_TYPE.MUTE_3D]: '禁言3天',
  [PUNISHMENT_TYPE.MUTE_7D]: '禁言7天',
  [PUNISHMENT_TYPE.PERMANENT_MUTE]: '永久禁言',
  [PUNISHMENT_TYPE.BAN]: '封号'
}

export const PUNISHMENT_DURATION = {
  [PUNISHMENT_TYPE.WARNING]: 0,
  [PUNISHMENT_TYPE.MUTE_1D]: 1,
  [PUNISHMENT_TYPE.MUTE_3D]: 3,
  [PUNISHMENT_TYPE.MUTE_7D]: 7,
  [PUNISHMENT_TYPE.PERMANENT_MUTE]: 36500,
  [PUNISHMENT_TYPE.BAN]: 36500
}

export const VIOLATION_LEVEL = {
  MINOR: 1,
  MODERATE: 2,
  SEVERE: 3,
  CRITICAL: 4
}

export const VIOLATION_PUNISHMENT_MAP = {
  [VIOLATION_LEVEL.MINOR]: PUNISHMENT_TYPE.WARNING,
  [VIOLATION_LEVEL.MODERATE]: PUNISHMENT_TYPE.MUTE_1D,
  [VIOLATION_LEVEL.SEVERE]: PUNISHMENT_TYPE.MUTE_7D,
  [VIOLATION_LEVEL.CRITICAL]: PUNISHMENT_TYPE.BAN
}
